services:
  pipeline:
    build:
      context: ./Pipeline
    volumes:
      - ./data:/data
      - ./reference:/reference
      - ./results:/results
    command: ["bash", "-c", "sleep infinity"]
    ports:
      - "5000:5000"

  leishweb:
    build:
      context: ./Leishweb
    ports:
      - "5001:5000"
    volumes:
      - ./data:/data
      - ./results:/results
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - pipeline