name: leish-env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _python_abi3_support=1.0=hd8ed1ab_2
  - _r-mutex=1.0.1=anacondar_1
  - alsa-lib=1.2.14=hb9d3cd8_0
  - anndata=0.11.4=pyhd8ed1ab_0
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - anyio=4.11.0=pyhcf101f3_0
  - argcomplete=3.6.2=pyhd8ed1ab_0
  - argon2-cffi=25.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=25.1.0=py310h7c4b9e2_1
  - array-api-compat=1.12.0=pyhe01879c_0
  - arrow=1.4.0=pyhcf101f3_0
  - asttokens=3.0.0=pyhd8ed1ab_1
  - async-lru=2.0.5=pyh29332c3_0
  - attrs=25.4.0=pyh71513ae_0
  - babel=2.17.0=pyhd8ed1ab_0
  - bcftools=1.22=h3a4d415_1
  - beautifulsoup4=4.14.2=pyha770c72_0
  - bedtools=2.31.1=h13024bc_3
  - binutils_impl_linux-64=2.44=hdf8817f_2
  - bioconductor-biobase=2.62.0=r43ha9d7317_3
  - bioconductor-biocgenerics=0.48.1=r43hdfd78af_2
  - bioconductor-biocio=1.12.0=r43hdfd78af_0
  - bioconductor-biocparallel=1.36.0=r43hf17093f_2
  - bioconductor-biostrings=2.70.1=r43ha9d7317_2
  - bioconductor-data-packages=20250625=hdfd78af_0
  - bioconductor-delayedarray=0.28.0=r43ha9d7317_2
  - bioconductor-genomeinfodb=1.38.1=r43hdfd78af_1
  - bioconductor-genomeinfodbdata=1.2.11=r43hdfd78af_1
  - bioconductor-genomicalignments=1.38.0=r43ha9d7317_1
  - bioconductor-genomicranges=1.54.1=r43ha9d7317_2
  - bioconductor-iranges=2.36.0=r43ha9d7317_2
  - bioconductor-matrixgenerics=1.14.0=r43hdfd78af_3
  - bioconductor-noiseq=2.46.0=r43hdfd78af_0
  - bioconductor-rhtslib=2.4.0=r43ha9d7317_2
  - bioconductor-rsamtools=2.18.0=r43hf17093f_2
  - bioconductor-rtracklayer=1.62.0=r43ha9d7317_1
  - bioconductor-s4arrays=1.2.0=r43ha9d7317_2
  - bioconductor-s4vectors=0.40.2=r43ha9d7317_2
  - bioconductor-sparsearray=1.2.2=r43ha9d7317_2
  - bioconductor-summarizedexperiment=1.32.0=r43hdfd78af_0
  - bioconductor-xvector=0.42.0=r43ha9d7317_2
  - bioconductor-zlibbioc=1.48.0=r43ha9d7317_2
  - biom-format=2.1.17=py310h139afa4_1
  - biopython=1.85=py310h7c4b9e2_2
  - bleach=6.2.0=pyh29332c3_4
  - bleach-with-css=6.2.0=h82add2a_4
  - brotli=1.1.0=hb03c661_4
  - brotli-bin=1.1.0=hb03c661_4
  - brotli-python=1.1.0=py310hea6c23e_4
  - bwa=0.7.19=h577a1d6_1
  - bwidget=1.10.1=ha770c72_1
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.4=h3394656_0
  - certifi=2025.10.5=pyhd8ed1ab_0
  - cffi=1.17.1=py310h8deb56e_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.0=pyh707e725_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - coloredlogs=15.0.1=pyhd8ed1ab_4
  - colormath=3.0.0=pyhd8ed1ab_4
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.2=py310h3788b33_0
  - cpython=3.10.19=py310hd8ed1ab_1
  - curl=8.14.1=h332b0f4_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.28=hd9c7081_0
  - dbus=1.13.6=h5008d03_3
  - debugpy=1.8.17=py310h25320af_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - double-conversion=3.3.1=h5888daf_0
  - et_xmlfile=2.0.0=pyhd8ed1ab_1
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.1=hecca717_0
  - fastp=1.0.1=heae3180_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.60.1=py310h3406613_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freetype=2.14.1=ha770c72_0
  - fribidi=1.0.16=hb03c661_0
  - gatk4=4.6.2.0=py310hdfd78af_1
  - gcc_impl_linux-64=15.2.0=hcacfade_7
  - gfortran_impl_linux-64=15.2.0=h1b0a18f_7
  - giflib=5.2.2=hd590300_0
  - graphite2=1.3.14=hecca717_2
  - gsl=2.7=he838d99_0
  - gxx_impl_linux-64=15.2.0=h54ccb8d_7
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - h5py=3.15.1=nompi_py310h4aa865e_100
  - harfbuzz=11.0.0=h76408a6_0
  - hdf5=1.14.6=nompi_h6e4c0c1_103
  - hpack=4.1.0=pyhd8ed1ab_0
  - htslib=1.22.1=h566b1c6_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - humanfriendly=10.0=pyh707e725_8
  - humanize=4.14.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - iniconfig=2.3.0=pyhd8ed1ab_0
  - ipykernel=7.0.1=pyha191276_0
  - ipython=8.37.0=pyh8f84b5b_0
  - isa-l=2.31.1=hb9d3cd8_1
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.2=pyhd8ed1ab_0
  - jq=1.5=0
  - json5=0.12.1=pyhd8ed1ab_0
  - jsonpointer=3.0.0=py310hff52083_2
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jsonschema-with-format-nongpl=4.25.1=he01879c_0
  - jupyter-lsp=2.3.0=pyhcf101f3_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_server=2.17.0=pyhcf101f3_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.4.9=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.27.3=pyhd8ed1ab_1
  - kaleido-core=0.2.1=h3644ca4_0
  - kernel-headers_linux-64=5.14.0=he073ed8_2
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.9=py310haaf941d_1
  - krb5=1.21.3=h659f571_0
  - lark=1.3.0=pyhd8ed1ab_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.44=ha97dd6f_2
  - legacy-api-wrap=1.4.1=pyhd8ed1ab_0
  - lerc=4.0.0=h0aef613_1
  - libaec=1.1.4=h3f801dc_0
  - libblas=3.9.0=37_h4a7cf45_openblas
  - libbrotlicommon=1.1.0=hb03c661_4
  - libbrotlidec=1.1.0=hb03c661_4
  - libbrotlienc=1.1.0=hb03c661_4
  - libcblas=3.9.0=37_h0358290_openblas
  - libclang-cpp20.1=20.1.8=default_h99862b1_4
  - libclang13=21.1.0=default_h746c552_1
  - libcups=2.3.3=hb8b1518_5
  - libcurl=8.14.1=h332b0f4_0
  - libdeflate=1.24=h86f0d12_0
  - libdrm=2.4.125=hb03c661_1
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=hd590300_2
  - libexpat=2.7.1=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-devel_linux-64=15.2.0=h73f6952_107
  - libgcc-ng=15.2.0=h69a702a_7
  - libgfortran=15.2.0=h69a702a_7
  - libgfortran-ng=15.2.0=h69a702a_7
  - libgfortran5=15.2.0=hcd61629_7
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.84.0=h2ff4ddf_0
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=15.2.0=h767d61c_7
  - libhwloc=2.12.1=default_h3d81e11_1000
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - liblapack=3.9.0=37_h47877c9_openblas
  - libllvm20=20.1.8=hecd9e04_0
  - libllvm21=21.1.0=hecd9e04_0
  - liblzma=5.8.1=hb9d3cd8_2
  - libnghttp2=1.67.0=had1ee68_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libntlm=1.8=hb9d3cd8_0
  - libopenblas=0.3.30=pthreads_h94d23a6_2
  - libopengl=1.7.0=ha4b6fd6_2
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.50=h421ea60_1
  - libpq=17.6=h3675c94_2
  - libsanitizer=15.2.0=hb13aed2_7
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.50.4=h0c1763c_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-devel_linux-64=15.2.0=h73f6952_107
  - libstdcxx-ng=15.2.0=h4852527_7
  - libtiff=4.7.1=h8261f1e_0
  - libuuid=2.41.2=he9a06e4_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.11.0=he8b52b9_0
  - libxml2=2.13.8=h04c0eec_1
  - libxslt=1.1.43=h7a3aeb2_0
  - libzlib=1.3.1=hb9d3cd8_2
  - llvmlite=0.45.1=py310hee1c697_0
  - make=4.4.1=hb9d3cd8_2
  - markdown=3.9=pyhd8ed1ab_0
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.3=py310h3406613_0
  - mathjax=2.7.7=ha770c72_3
  - matplotlib=3.10.7=py310hff52083_0
  - matplotlib-base=3.10.7=py310hfde16b3_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mdurl=0.1.2=pyhd8ed1ab_1
  - mistune=3.1.4=pyhcf101f3_0
  - multiqc=1.31=pyhdfd78af_0
  - munkres=1.0.7=py_1
  - mysql-common=9.0.1=h266115a_6
  - mysql-libs=9.0.1=he0572af_6
  - narwhals=2.8.0=pyhcf101f3_0
  - natsort=8.4.0=pyh29332c3_1
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert-core=7.16.6=pyhcf101f3_1
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.4.2=pyh267e887_2
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - nspr=4.37=h29cc59b_0
  - nss=3.117=h445c969_0
  - numba=0.62.1=py310h3477d8a_0
  - numpy=2.2.6=py310hefbff90_0
  - openjdk=23.0.2=h53dfc1b_2
  - openjpeg=2.5.4=h55fea9a_0
  - openldap=2.6.10=he970967_0
  - openpyxl=3.1.5=py310h05b0c27_2
  - openssl=3.5.4=h26f9b46_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py310h0158d43_1
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - pango=1.56.3=h9ac818e_1
  - parso=0.8.5=pyhcf101f3_0
  - patsy=1.0.1=pyhd8ed1ab_1
  - pcre2=10.44=hc749103_2
  - perl=5.32.1=7_hd590300_perl5
  - pexpect=4.9.0=pyhd8ed1ab_1
  - picard=3.4.0=hdfd78af_0
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.3.0=py310h6557065_3
  - pip=25.2=pyh8b19718_0
  - pixman=0.46.4=h54a6638_1
  - platformdirs=4.5.0=pyhcf101f3_0
  - plotly=6.3.1=pyhd8ed1ab_0
  - pluggy=1.6.0=pyhd8ed1ab_0
  - polars=1.34.0=pyh6a1acc5_0
  - polars-lts-cpu=1.34.0.deprecated=hc364b38_0
  - polars-runtime-32=1.34.0=py310hffdcd12_0
  - polars-runtime-compat=1.34.0=py310hbcd5346_0
  - prometheus_client=0.23.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.0=py310h7c4b9e2_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pyaml-env=1.2.2=pyhd8ed1ab_0
  - pycparser=2.22=pyh29332c3_1
  - pydantic=2.12.3=pyh3cfb1c2_0
  - pydantic-core=2.41.4=py310hd8f68c5_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pynndescent=0.5.13=pyhd8ed1ab_1
  - pyparsing=3.2.5=pyhcf101f3_0
  - pysam=0.23.3=py310h64e62c9_1
  - pyside6=6.9.0=py310hfd10a26_0
  - pysocks=1.7.1=pyha55dd90_7
  - pytest=8.4.2=pyhd8ed1ab_0
  - python=3.10.19=hd994cfb_1_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-dotenv=1.1.1=pyhe01879c_0
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-gil=3.10.19=hd8ed1ab_1
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-kaleido=0.2.1=pyhd8ed1ab_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.10=8_cp310
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.3=py310h3406613_0
  - pyzmq=27.1.0=py310h4f33d48_0
  - qhull=2020.2=h434a139_5
  - qt6-main=6.9.0=h6441bc3_0
  - qualimap=2.3=hdfd78af_0
  - r-abind=1.4_5=r43hc72bb7e_1006
  - r-base=4.3.3=h5074ccb_16
  - r-bh=1.87.0_1=r43hc72bb7e_0
  - r-bitops=1.0_9=r43h2b5f3a1_0
  - r-codetools=0.2_20=r43hc72bb7e_1
  - r-cpp11=0.5.2=r43h785f33e_1
  - r-crayon=1.5.3=r43hc72bb7e_1
  - r-formatr=1.14=r43hc72bb7e_2
  - r-futile.logger=1.4.3=r43hc72bb7e_1006
  - r-futile.options=1.0.1=r43hc72bb7e_1005
  - r-getopt=1.20.4=r43ha770c72_1
  - r-lambda.r=1.2.4=r43hc72bb7e_4
  - r-lattice=0.22_7=r43h2b5f3a1_0
  - r-matrix=1.6_5=r43he966344_1
  - r-matrixstats=1.5.0=r43h2b5f3a1_0
  - r-optparse=1.7.5=r43hc72bb7e_1
  - r-rcurl=1.98_1.17=r43hb79926e_0
  - r-restfulr=0.0.15=r43h56115f1_4
  - r-rjson=0.2.23=r43h93ab643_0
  - r-snow=0.4_4=r43hc72bb7e_3
  - r-xml=3.99_0.17=r43h5bae778_2
  - r-yaml=2.3.10=r43hdb488b9_0
  - readline=8.2=h8c095d6_2
  - referencing=0.37.0=pyhcf101f3_0
  - regex=2025.9.18=py310h7c4b9e2_0
  - requests=2.32.5=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rfc3987-syntax=1.1.0=pyhe01879c_1
  - rich=14.2.0=pyhcf101f3_0
  - rich-click=1.9.3=pyhd8ed1ab_0
  - rpds-py=0.27.1=py310hd8f68c5_1
  - samtools=1.22.1=h96c455f_0
  - scanpy=1.11.4=pyhd8ed1ab_0
  - scikit-bio=0.7.0=py310hf779ad0_1
  - scikit-learn=1.7.2=py310h228f341_0
  - scipy=1.15.2=py310h1d65ade_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - sed=4.9=h6688a6e_0
  - send2trash=1.8.3=pyh0d859eb_1
  - session-info2=0.2.3=pyhd8ed1ab_0
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - sniffio=1.3.1=pyhd8ed1ab_1
  - snpeff=5.3.0a=hdfd78af_1
  - soupsieve=2.8=pyhd8ed1ab_0
  - spectra=0.0.11=pyhd8ed1ab_2
  - sqlite=3.50.4=hbc0de68_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.5=py310hf779ad0_1
  - sysroot_linux-64=2.34=h087de78_2
  - tbb=2022.2.0=hb60516a_1
  - terminado=0.18.1=pyh0d859eb_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tiktoken=0.12.0=py310h790759e_1
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.13=noxft_hd72426e_102
  - tktable=2.10=h8d826fa_7
  - toml=0.10.2=pyhd8ed1ab_1
  - tomli=2.3.0=pyhcf101f3_0
  - tomlkit=0.13.3=pyha770c72_0
  - tornado=6.5.2=py310h7c4b9e2_1
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typeguard=4.4.4=pyhd8ed1ab_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing-inspection=0.4.2=pyhd8ed1ab_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025b=h78e105d_0
  - umap-learn=0.5.9.post2=py310hff52083_0
  - unicodedata2=16.0.0=py310h7c4b9e2_1
  - uri-template=1.3.0=pyhd8ed1ab_1
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wayland=1.23.1=h3e06ad9_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - webcolors=24.11.1=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.9.0=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - xcb-util=0.4.1=h4f16b4b_2
  - xcb-util-cursor=0.1.5=hb9d3cd8_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.46=hb03c661_0
  - xmltodict=1.0.2=pyhcf101f3_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.2=hb03c661_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxt=1.3.1=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.6=hb9d3cd8_0
  - yaml=0.2.5=h280c20c_3
  - yq=3.4.3=pyhe01879c_2
  - zeromq=4.3.5=h387f397_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb9d3cd8_2
  - zstandard=0.25.0=py310h139afa4_0
  - zstd=1.5.7=hb8e6e7a_2